name: Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m textblob.download_corpora
      - name: Run tests
        run: |
          python -m pytest bad_commit_message_blocker_tests.py
